config/routes.rb
Rails.application.routes.draw do
  get 'callbacks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  # when people typed "localhost:3000" 
  # it's sending a http get request to this path "localhost:3000"
  # it will be handled by "WelcomeController" the "index" action
  # as: 'root'
  # This defines a route rule that says when we receive
  # a GET request with the URL '/', handle it with the
  # WelcomeController with the index action inside that
  # controller.

  get "/auth/github", as: :sign_in_with_github
  get "auth/:provider/callback", to: "callbacks#index"
  

  get('/', {to: 'welcome#index', as: 'root'})
  get('/goodbye',{to:'welcome#goodbye', as: :goodbye})
  get('/form_example',{to:'welcome#form_example'})

  # RESTful routes
  #A RESTful route provides mapping from HTTP verbs (like GET, POST, PATCH, PUT, DELETE)
  #to the contoller CRUD actions (create, read, update, destroy).
  #It depends on the HTTP verb and the URL, and not just solely on the URL

  #RESTful Routes for Questions resource
  #1 index: GET "/resources" - return all records of that resource
  #2 show: GET "/resources/:id" - returns one instance of the resource
  #3 new: GET "/resources/new" - return a view page with form to create a resource
  #4 create: POST "/resources" - handle the submission to the "new form" and inserts a new resource in the db
  #5 edit: GET "/resources/:id/edit" - returns a view form to edit an existing resource
  #6 update: PATCH "/resources/:id" - handle submission of the "edit form" and update the resource with specific id in the db
  #7 destroy: DELETE "/resources/:id" - delete a record with specific id from the database
  
  # get('/questions', {to: 'questions#index', as: :questions})
  # get('/questions/new',{to: 'questions#new'})
  # # The :as option creates a named path.
  # # You can then call this path in your controllers and views (e.g. redirect_to question_path) etc.
  # get('/questions/:id',{to: 'questions#show', as: :question })

  # delete('/questions/:id',{to: 'questions#destroy'})

  # post('/questions',{to: 'questions#create'})

  # get('/questions/:id/edit',{to: 'questions#edit', as: :edit_question })

  # patch('/questions/:id',{to: 'questions#update'})

  resources :questions do
    # Routes written inside of a block passed a resource method will be prefixed by
    # a path corresponding to the passed in symbol
    # in this case, all nested routes will be pre-fixed with '/questions/:question_id'
    resources :answers, only:[:create, :destroy]
    # resources :answers, except: [:show, :new, :index, :edit, :update]
    
    resources :likes, shallow: true, only:[:create, :destroy]
    # The `shallow: true` named argument will separate routes taht require the parent
    # from thos that don't. Routes that require the parent won't be changed (i.e. index, new, create)
    # Rouhtes that don't require the parent (i.e. show, edit, update, destroy) will have the parent 
    # prefix (/questions/:question_id) removed
    # for destroy => /questions/1/likes/5 => /likes/5

    get :liked, on: :collection
    # GET "/questions/liked" 

  end

  resources :users, only:[:new, :create]

  resource :session, only: [:new, :create, :destroy]
  # `resource` is singular instead of `resources`
  # Unlike `resources`, `resource` will create routes that do CRUD opreation
  # on only one thing. Also there will be no index reoutes, and no route will
  # have an `:id` wildcard. but the controller name is still plural

  resources :job_posts, only: [:new, :create, :show, :index, :destroy, :edit, :update]

   #Delayed Job Routes:
  #We will go to this url to see this route: 'localhost:3000/delayed_job/overview'
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )
  # https://guides.rubyonrails.org/active_job_basics.html #👈🏻 Link for active jobs

  # restful routes
  # /api/questions
  namespace :api, defaults: {format: :json} do
    # The namespace method in Rails routes makes it automatically prepend a /api infront of the routes
    # The option `defaults: {format: :json} will set json as the default response for all routes contained within this namespace block`
    #/api
    namespace :v1 do
      # /api/v1/questions
      resources :questions
      resource :session, only: [:create, :destroy]
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
    after_initialize :set_defaults
    before_save :capitalize_title
    
    has_many :answers, dependent: :destroy

    belongs_to :user

    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings#, source: :tag
    #if the name of the association (i.e. tags) is the same as the
    #source singularized (i.e. tag), then the 'source' named argument
    #can be omitted


    validates :title, presence: {message: "must be provided"}, uniqueness: {scope: :body}, length: { minimum: 2, maximum: 200 }

    #unique to the scope of body means title doesn't need to be unique 
    #on its own, but does have to be unique in combination to the body

    validates :view_count, numericality: {greater_than_or_equal_to: 0}

    # Custom Validation
    # Be careful, the method for custom validations is
    # singular and its almost exactly same the method
    # for regular validations.
    validate :no_monkey

    # has_and_belongs_to_many(
    #     :likes,
    #     {
    #         class_name:'User',
    #         join_table: 'likes',
    #         association_foreign_key: 'user_id',
    #         foreign_key: 'question_id'
    #     }
    # )
    # :class_name => the model that the association points to
    # :join_table => the join table used to create this association
    # :foreign_key => on the join table, which foreign key points to this current model
    # : association_foreign_key => on the join table, which foreign key points the associated table


    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
    

     # The has_may can take an argument `through` => `:likes` is the name of 
    # another has_association => `has_many :likes`


    def no_monkey
        # &. is the safe navigation operator. It's used like . operator
        # to call methods of the object
        # if the body donesn't exist, 'nil' in JS might be undefined or null
        # this will return nil instead of getting an error
        if body&.downcase&.include?("monkey")
            self.errors.add(:body, "Must not have monkey")
        end
    end


    #-----------ADD CUSTOM TAG METHODS TO GET OR SET TAGS WITH SELECTIZE------>

    #Getter
    def tag_names
        self.tags.map(&:name).join(", ")
        #The & symbol is used to tell Ruby that the following argument
        #should be given as a block to the method. So the line:
        #self.tags.map(&.:name).join(", ") is equal to
        #self.tags.map { |t| t.name.join(", ")}
        #So the above will iterate over tyhe collection of elf.tags
        #and build an array with the resukts of the name method
        #called on every item
    end

    #Setter
    #This is similar to implementing an attribute writer "attr_writer"
    #Appending = at the end of a method name allows us to implement a setter
    #A setter is a method that is assignable, example:
    # q.tag_names = 'another new tag name'
    def tag_names=(rhs)
        self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
            Tag.find_or_initialize_by(name: tag_name)
        end
    end


    
    private

    def set_defaults
        # self.view_count = 0 if self.view_count.nil?
        # self.view_count = self.view_count || 0
        self.view_count ||= 0
    end

    def capitalize_title
        self.title.capitalize!
    end

    # def self.recent_ten
    #     order("created_at DESC").limit(10)
    # end

    scope :recent_ten, lambda { order("created_at DESC").limit(10)}

    # Scopes are such a commonly used feature that there's a way to 
    # create them quicker. It takes a name and a lambda as a callback
    scope :wildcard_search, ->(search_query) { where("title ILIKE '%#{search_query}%' or body ILIKE '%#{search_query}%' ") }

    # def self.wildcard_search(search_query)
    #     where("title ILIKE ? OR body ILIKE ?","%#{search_query}%","%#{search_query}%")
    # end
    
    # select * from questions where title ilike %??% and body ilike %???%;
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::ApplicationController
    # this controller is generated by rails g controller api/v1/questions --no-assets --no-helper --skip-template-engine
    # also remember to change the parent class => Api::ApplicationController

    before_action :authenticate_user!, except: [:index, :show]

    def index
        # return all the questions in json format
        questions = Question.order(created_at: :desc)
        render(json: questions, each_serializer: QuestionCollectionSerializer)
    end

    def show
        # return a single question in json format
        question = Question.find params[:id]
        render(json: question)
    end
    
    def create
        # when user send a request generate a new question
        # response failed or success

        question = Question.new(params.require(:question).permit(:title,:body))
        question.user = current_user
        if question.save
            render json:{id: question.id}
        else
            render json:{errors:question.errors, status:422}
        end
    end
    
    def destroy
        # based on the id of the user requset, delete that question
        question = Question.find(params[:id])        
        if question.update(params.require(:question).permit(:title,:body))
            render json: {id: question.id}
        else
            render json:{ errors:question.errors, status: 422}
        end
    end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    # rails g controller questions --no-helper --no-assets
    # if you don't need helper.rb and questions.scss files
    # you can add those options when you run rails g controller
    before_action :find_question, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user! , except: [:index, :show]
    before_action :authorize_user!, only: [:update, :destroy]

    def index
        #@questions = Question.all.order(created_at: :desc)
        # Model.all is a method built into actice record used to return
        # all records of that model
        # thi sign @ is necessary to make the variable to the view pages
        # it is called an "instance variable"
        if params[:tag]
            @tag = Tag.find_or_initialize_by(name: params[:tag])
            @questions = @tag.questions.order('updated_at DESC')
        else
            @questions = Question.order(created_at: :desc)

            respond_to do |format|
                format.html {render}
                format.json {render json: @questions}
            end
        end
    end

    def show
        @answers = @question.answers.order(created_at: :desc)
        @answer = Answer.new
        @like = @question.likes.find_by(user: current_user)
    end
    
    def destroy
        @question.destroy
        redirect_to questions_path
    end
    
    def new
        @question = Question.new
    end

    def create
        # get the data from the form and add it into DB
        # User the  `require` on the params object to retrieve the nested hash of a key
        # usually corresponding the na-value pairs of a form
        # `permit` to specify all input names are  allowed to submit to the DB
        # @question = Question.new(params.require(:question).permit(:title,:body))
        @question = Question.new(question_params)
        @question.user = current_user
        if @question.save
            flash[:notice] = "Question created successfully!"
            redirect_to question_path(@question.id)
        else
            render :new
        end

    end

    def edit
        
    end
    
    def update
        if @question.update(question_params)
            redirect_to question_path(@question.id)
        else
            render :edit
        end 
    end
    

    def liked
      @questions = current_user.liked_questions
    end
    

    private 
   

    def find_question
        @question = Question.find params[:id]
    end
    
    def question_params
        params.require(:question).permit(:title,:body, :tag_names)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not Authorized!" unless can?(:crud, @question)
    end
    
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
    <ul>
        <% @question.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <% end%>
    </ul>
<% end%>
<%= form_with(model: @question) do |form|%>

<div class="form-group">
    <%= form.label :title%>
    <br>
    <%= form.text_field :title ,class:"form-text" , autofocus: true   %>
</div>
<div class="form-group">
    <%= form.label :body%>
    <br>
    <%= form.text_area :body, cols: 50, rows: 5 ,class:"form-text" %> 
 <div class="tag-wrapper">
    <%= form.label :tag_names %>
    <%= form.text_field :tag_names %>
    </div>
<%= form.submit %>

<% end%>

<script>
    <%# selectize doc:
    https://github.com/selectize/selectize.js/blob/master/docs/usage.md
    %>
    $(function(){
        $('#question_tag_tames').selectize({
            delimeter: ',',
            persist: false,
            labelField: 'name', //Column name in db  
            valueField: 'name', //Column name in db
            searchField: 'name', //Column in db
            options: <% Tag.select(:name).to_json(except: [:id]).html_safe %>,
            //The above line selects only names from tags table and converts them to
            //a json array of objects without including ids and makes sure its safe html string
            //options: [{"name": "first tag"}, {"name":"second tag"}, ..., {"name": "last tag"}]
            create: function(input) {
                return {
                    name: input
                }
            }
        })
    })
</script>

app/views/questions/edit.html.erb
<h1>
    Question Edit Page
</h1>

<%= render "form" %>

app/views/questions/edit_old.html.erb
<h1>
    Question Edit Page
</h1>


<%= form_with(model: @question) do |form|%>

<div class="form-group">
    <%= form.label :title  %>
    
    <%= form.text_field :title ,class:"form-text" , autofocus: true   %>
</div>
<div class="form-group">
    <%= form.label :body%>
    <br>
    <%= form.text_area :body, cols: 50, rows: 5 ,class:"form-text"    %>
</div>
<%= form.submit %>

<% end%>

app/views/questions/index.html.erb
<h1>
    Question Index Page
</h1>

<% if @tag.present? %>
    <h2>Showing Questions tagged by: 
        <span class="badge badge-pill badge-primary"><%= @tag.name %></span>
    </h2>
<% end%>

<% @questions.each do |question|%>
    <div>
        <h3>

        <%# question.title%>
        <h2><%= link_to(question.title, question_path(question.id)) %></h2>
        </h3>
        <p>
        <%= question.body%>
        </p>
    </div>
<% end %>

app/views/questions/liked.html.erb
<h1>
Liked Questions
</h1>

<div class="row">
    <div class="col-2">
    </div>
    <div class="col-10">
        <% @questions.each do |question|%>
            <div>
                <h3> <%= link_to question.title, question_path(question) %> </h3>
                <hr />
            </div>
        <% end%>
    </div>
</div>

app/views/questions/new.html.erb
<h1>
    Question New Page
</h1>

<%= render "form" %> 

app/views/questions/show.html.erb
<h1>
    Question Show Page
</h1>

<h3>
<%= @question.title%>
</h3>

<p>
<%= @question.body%>
</p>
<p><strong>Tags:</strong><%= @question.tags.map(&:name).join(", ") %></p>

<% unless @question.tags.empty? %>
    <p> Tags:
        <% @question.tags.each do |tag| %>
        <%= link_to(
            tag.name, questions_path(tag: tag.name),
            class: 'badge badge-pill badge-primary'
        )%>
        <% end %>
    </p>
<% end %>
<p>
<%= time_ago_in_words(@question.created_at) %> ago
</p>
<p>
<%= @question.created_at%>
</p>
<p>
<%= @question.updated_at%>

<h5>
    Created by: <%= @question.user.first_name %>
</h5>
</p>
<% if can?(:crud, @question)%>
<%= link_to("Delete", question_path(@question.id), method: :delete, data: {confirm: "Are you sure"}) %>

<%= link_to("Edit", edit_question_path(@question.id)) %>

<% end %>


<% if @like.present? %>
<%= link_to "Unlike", like_path(@like), method: :delete %>
<% else %>
<%= link_to "Like", question_likes_path(@question), method: :post %>
<% end %>
<small>Liked by: <%= @question.likes.count %> users</small>
 


<ul>
<% @answers.each do |answer| %>
    <li>
        <%= answer.body%>
        <small>
            Answered <%= time_ago_in_words(answer.created_at) %> ago
        </small>

        <% if can?(:crud, answer)%>
        <%# link_to "Delete", question_answer_path(@question, answer), method: :delete, data:{confirm: "Are you sure"}  %>

        <%= link_to "Delete", question_answer_path(@question.id, answer.id), method: :delete, data:{confirm: "Are you sure"}  %>
         <% end %>
    </li>
<% end %>
</ul>
<p>
<% if @answer.errors.any? %>
    <ul>
    <% @answer.errors.full_messages.each do |msg| %>
        <li> <%= msg%> </li>
    <% end%>
    </ul>
<% end%>

<%= form_with(model:[@question, @answer]) do |f|%>
    <div>
        <%= f.label :body%>
        <br>
        <%= f.text_area :body, cols: 50, rows: 5 %>
    </div>
    <%= f.submit "Answer"%>
<% end %>

<p>
<a href="/questions">back to index</a>